name: Build Phar

on:
    push:
        branches: [ master ]
    pull_request:
    release:
        types: [ created ]

jobs:
    build-phar:
        runs-on: ubuntu-latest
        name: Build PHAR
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.0', '8.1' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: phar.readonly=0
                    tools: composer
                    coverage: none

            -   name: Install Composer dependencies
                uses: ramsey/composer-install@v2

            -   name: Install RequirementChecker Composer dependencies
                uses: ramsey/composer-install@v2

            -   name: Build PHAR
                run: ./music-dl app:build --build-version=$(git describe --abbrev=0 --tags)

            # Smoke test
            -   name: Ensure the PHAR works
                run: builds/music-dl --version

            -   uses: actions/upload-artifact@v3
                name: Upload the PHAR artifact
                with:
                    name: music-dl
                    path: builds/music-dl

    publish-phar:
        runs-on: ubuntu-latest
        name: Publish the PHAR
        needs:
            - 'build-phar'
        steps:
            -   uses: actions/download-artifact@v3
                with:
                    name: music-dl
                    path: .

            -   name: Upload music-dl
                uses: softprops/action-gh-release@v1
                if: startsWith(github.ref, 'refs/tags/')
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    files: builds/music-dl
