name: "bump version"

on:
  release:
    types: [ released ]

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --no-suggest --prefer-dist --no-dev"

jobs:
  update:
    runs-on: ubuntu-latest
    name: Build PHAR
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
        with:
          ref: master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: phar.readonly=0
          tools: composer
          coverage: none

      - name: Install dependencies
        run: "composer install ${{ env.COMPOSER_FLAGS }}"

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Build PHAR
        run: ./music-dl app:build --build-version=${{ github.event.release.name }}

      - name: Commit bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: Bump to ${{ github.event.release.name }}
          file_pattern: builds/music-dl CHANGELOG.md
