name: "update phar"

on:
  release:
    types: [ released ]

jobs:
  update:
    runs-on: ubuntu-latest
    name: Build PHAR
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: phar.readonly=0
          tools: composer
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Build PHAR
        run: ./music-dl app:build --build-version=$(git describe --abbrev=0 --tags)

      - name: Commit updated phar
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: Bump to ${{ github.event.release.name }}
          file_pattern: builds/music-dl
